### ISSUE TITLE
SimpleSAML_Error_NoState: NOSTATE error

### ISSUE THREAD

**Issue by jhaar** [pitbulk/apps#2]
Hi there

I have SSP installed as an SP and have successfully used the "test authentication sources" tab to confirm it is talking to our SSP IdP correctly - so I think the SSP framework is in place for user_saml to use correctly

However, when I enabled it, there were problems
1. saml_ssp_path in settings.php never worked. I had to hard-wire it into auth.php and user_saml.php to get past this problem.
2. after configuring it within owncloud successfully (enabled, checks mappings, etc), bringing up a fresh browser didn't show the SAML login form. I discovered that if I deliberately failed a login, then the new login form with SAML showed up!
3. after attempting to login via SAML, I get redirected to the IdP. I login, get redirected back to the owncloud SP and then the following error occurs

SimpleSAML_Error_NoState: NOSTATE
Backtrace:
2 /simplesamlphp-1.10.0/lib/SimpleSAML/Auth/State.php:232 (SimpleSAML_Auth_State::loadState)
1 /simplesamlphp-1.10.0/modules/saml/www/sp/saml2-acs.php:54 (require)
0 /simplesamlphp-1.10.0/www/module.php:135 (N/A)

I'm just using php sessions, and their contents show SSP data, so I think the cookies are OK...

Any ideas? This is CentOS-6 running php-5.3.18 and simplesamlphp-1.10.0 with owncloud-4.5.2

Thanks!

Jason

**Comment by pitbulk** [comment]
Hi,

Maybe is a problem with the new version of owncloud.
I will try to reproduce the problems and fix them right now.

**Comment by pitbulk** [comment]
Hi @jhaar.

I found several compatibility problems between my plugin and the OwnClound 4.5.2

I created a new branch with changes (https://github.com/pitbulk/apps/tree/experiment)
Check if this new version fix your problems.

**Comment by jhaar** [comment]
Much better. That has fixed the saml_ssp_path problem - but the SAML login option still doesn't show up. However, if you know the "/apps/user_saml/auth.php" link, it works perfectly :-)

One thing: can you figure out how to disable the password field in "Personal" settings? Obviously if a user is logged in via SAML, there is no local password to change

Finally, my problem "3" was at my end. I was confused as to the relationship between simplesamlphp and your work.  Once I figured that out, it all worked

Anyway, all good stuff. Thanks!

**Comment by pitbulk** [comment]
No SAML link?    is javascript enable on your browser? Other thing that can happen is that the changes on the app dont take effect due you had installed a previous version. Read the Readme.md and follow the "notes" instruction that tlak about edit the index.php at the base of owncloud and change the value of the param that happears there.

Why you need disable the password option? Imagine that I used the SAML way to access the platform and a new account was created with a random password. Since there are protocols like caldav, webdav, carddav is a good idea to let the user set a password there in order to use this credential for them.

**Comment by jhaar** [comment]
Very strange. If I use curl to download the frontpage, there is no "remote.php/core.js" in it. If I use "curl -dusername.." I get the error page and remote.php/core.js is now present - and that contains the SAML login stuff. That's why I only see it after the first failed login

For the second point, it all depends what you are using SAML for. What you are suggesting is OK for some I guess, but I would have thought the primary reason to use SAML is for centralized account management - and ensuring a user who has been fired cannot get into SPs afterwards is one of the key features. Allowing them to override the centralization is precisely what we don't want to happen

**Comment by pitbulk** [comment]
The App was configured as 'authentication', so was only loaded if a credential was sent. I change that and defined the App also as prelogin' to load the App when user is not authenticated.  Seems that this change not take effect if you had already had the plugin.

If you want to disable the normal authentication method you will need to hack a little my plugin and the  owncloud.e
1. In order to remove all the normal form you can go to user_saml/js/utils.js and change the logic to remove always all the normal login form.  Or delete all the logic related to hide the form and delete also the content of the core/templates/login.php
2. Disable paswwordreset and passwordchange at core/templates/lostpassword/controller.php
3. Return always false in the normal login. Change that at lib/user/database.php in checkPassword function.
